#!/bin/bash

echo "Setting up virtual keyboard"

# Create gadget
cd /sys/kernel/config/usb_gadget
mkdir -p virtual_keyboard
cd virtual_keyboard

# Add basic information
echo 0x0100 > bcdDevice # Version 1.0.0
echo 0x0200 > bcdUSB # USB 2.0
echo 0x00 > bDeviceClass
echo 0x00 > bDeviceProtocol
echo 0x00 > bDeviceSubClass
echo 0x08 > bMaxPacketSize0
echo 0x0104 > idProduct # Multifunction Composite Gadget
echo 0x1d6b > idVendor # Linux Foundation

# Create English locale
mkdir -p strings/0x409

echo "Virtual keyboard manufacturer" > strings/0x409/manufacturer
echo "Virtual Keyboard" > strings/0x409/product
echo "0123456789" > strings/0x409/serialnumber

# Create HID function
mkdir -p functions/hid.usb0

echo 1 > functions/hid.usb0/protocol
echo 7 > functions/hid.usb0/report_length # 7-byte reports
echo 1 > functions/hid.usb0/subclass
echo "05010906a101050719e029e71500250175019508810275089506150026ff0019002aff008100c0" | xxd -r -ps > functions/hid.usb0/report_desc

# Create configuration
mkdir -p configs/c.1
mkdir -p configs/c.1/strings/0x409

echo 0x80 > configs/c.1/bmAttributes
echo 200 > configs/c.1/MaxPower # 200 mA
echo "Example configuration" > configs/c.1/strings/0x409/configuration

# Link HID function to configuration
ln -s functions/hid.usb0 configs/c.1

# Enable gadget
ls /sys/class/udc > UDC

echo "Finished setting up virtual keyboard"
